### ISSUE TITLE
[FE] 버튼 및 라벨 공통 컴포넌트 작업

### ISSUE THREAD

**Issue by rockbell89** [codestates-seb/seb42_main_002#33]
아래 내용은 전부 예제입니다. 수정해서 사용하세요.

## Todo 추가 기능
- [x] 버튼 공통 컴포넌트 작업
- [x] 라벨 공통 컴포넌트 작업
- [x] 모달 공통 컴포넌트 작업

### 작업 예상 시간
18
